wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705465585.701578
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 12
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.8.16
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
