wandb_version: 1

batch_size:
  desc: null
  value: 102
fc_layer_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.03592044134647521
num_epochs:
  desc: null
  value: 50
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705477449.570713
    t:
      1:
      - 1
      - 5
      - 12
      - 53
      - 55
      2:
      - 1
      - 5
      - 12
      - 53
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.8.16
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
