wandb_version: 1

batch_size:
  desc: null
  value: 252
fc_layer_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.007747389093847457
num_epochs:
  desc: null
  value:
  - 20
  - 25
  - 30
optimizer:
  desc: null
  value: sgd
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705472183.316491
    t:
      1:
      - 1
      - 5
      - 12
      - 53
      - 55
      2:
      - 1
      - 5
      - 12
      - 53
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.8.16
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
